export default {
  Gluten: "icon-gluten_SFontCN",
  Schaaldieren: "icon-shrimp",
  Eieren: "icon-egg",
  Vis: "icon-fish",
  Pinda: "icon-peanut",
  Soja: "icon-icon-soya",
  Melk: "icon-milk",
  Noten: "icon-nutsfun-font",
  Selderij: "icon-icons-celery",
  Mosterd: "icon--MustardFlat",
  Sesamzaad: "icon-Sesame",
  "Zwaveldioxide en sulfiet": "icon-icon-sulphurdioxide",
  Lupine: "icon-yushandou",
  Weekdieren: "icon-icons-shellfish",
  Vegetarisch: "icon-vegan",
  "18+": "icon-a-18plus",
  "Spicy hot": "icon-a-pngfindcom-pepper-png-108422-copy",
  "Spicy medium": "icon-a-pngfindcom-pepper-png-108422",
  "Spicy mild": "icon-a-pngfindcom-pepper-png-108422-copy-copy",
  Halal: "icon-halal",
};
